### ISSUE TITLE
undefined is not an object (evaluating 'this.config.exclude') in line 40

### ISSUE THREAD

**Issue by maikischa** [CFenner/MagicMirror-Sonos-Module#15]
Hi,

if I run your script i get this error in line 40.
It seems that this.config is not defined. Did i missed something. The widget shows: "Loading music"

Thx. Andi

**Comment by CFenner** [comment]
Did you set exclude in your config? By default it is set to `[]`, so it shouldn't be null.

BTW: Line 40 is not correct, `this.config.exclude`is only used in line 39 or 45. Is your code up to date?

**Comment by maikischa** [comment]
I used the config from the realm.md:

{
    module: 'sonos',
    position: 'top_right', // you may choose any location
    config: {}
}

**Comment by maikischa** [comment]
Also tired this config, but got the same error message:
{
    module: 'sonos',
       position: 'bottom_right', // you may choose any location
         config: {
            showStoppedRoom: false,
             showRoomName: true,
             showAlbumArt: true,
             exclude: ['Wohnzimmer']
         }
},

**Comment by CFenner** [comment]
So this is solved? What was wrong?

**Comment by maikischa** [comment]
No, still the same error. Completely reinstalled magic mirror and the sonos module on a blank raspberry installation. 
Still the error on line 39
If i comment the section out, the module works

**Comment by CFenner** [comment]
hm.. Is this working for you right now?

I'm not at home for Christmas. I'll can have a look at it on my mirror next year.
